name: Docker hub
 
on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  CONTAINER_NAME: mspolyak-website
  LOGIN: ${{ secrets.DOCKER_LOGIN_D }}

  
jobs:
  build-and-push:
    name: GitHub-runner
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        
      - name: login
        uses: docker/login-action@v1.13.0
        with:
          username: ${{ env.LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD_D }}

      - name: Extracting metadata
        id: meta
        uses: docker/metadata-action@v3.6.2
        with:
          images: ${{ env.LOGIN }}/${{ env.CONTAINER_NAME }}:main

      - name: Build and Push to Packages
        uses: docker/build-push-action@v2.9.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

    
  remote_stop:
    needs: build-and-push
    name: remote-stopper
    runs-on: self-hosted
    
    steps:
      - name: container stop
        run: docker stop ${{env.CONTAINER_NAME}}
        
      - name: rmi
        id: ghrmi
        run: docker rmi ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:main
        
      - name: docker rmi
        if: ${{ steps.ghrmi.failure() }}
        run: docker rmi ${{ env.LOGIN }}/${{ env.CONTAINER_NAME }}:main

  remote_run:
    if: ${{ always() }}
    needs: remote_stop
    name: remote-runner
    runs-on: self-hosted
    
    steps:
      - name: docker pull
        run: docker pull ${{ env.IMAGE_NAME }}:main

      - name: run
        run: docker run --name ${{env.CONTAINER_NAME}} --rm -d -p 4000:80 ${{ env.LOGIN }}/${{ env.CONTAINER_NAME }}:main
  


