name: Full remote 

env:
  REGISTRY: ghcr.io
  CONTAINER_NAME: mspolyak-website
  IMAGE_NAME: ${{ github.repository }}
  
on:
  workflow_dispatch:
  
jobs:
  stop_prev_cont:
    name: stop previous container
    runs-on: self-hosted
    steps:
      - name: container stop
        run: docker stop ${{env.CONTAINER_NAME}}
        
      - name: rmi
        run: docker rmi ${{ env.REGISTRY }}/${{ env.IMAGE_PATH }}:main

    
  build:
    if: ${{ always() }}
    needs: stop_prev_cont
    name: image build
    runs-on: self-hosted
    steps:
      - name: checking for actual
        uses: actions/checkout@v2.4.0
        with:
          path: .
        
      - name: building
        run: docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_PATH }}:main .
        
      - name: running
        run: docker run --name ${{env.CONTAINER_NAME}} --rm -d -p 4000:80 ${{ env.REGISTRY }}/${{ env.IMAGE_PATH }}:main
