name: docker-compose
 
on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  CONTAINER_NAME: mspolyak-website

  
jobs:
  build-and-push:
    name: GitHub-runner
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        
      - name: login
        uses: docker/login-action@v1.13.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extracting metadata
        id: meta
        uses: docker/metadata-action@v3.6.2
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and Push to Packages
        uses: docker/build-push-action@v2.9.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  compose_up:
    name: Docker-compose up
    runs-on: self-hosted
    needs: build-and-push
    steps:
      - name: Pull latest
        run: docker pull ghcr.io/nwebiestudio/mspolyak-website:main

      - name: Docker-compose up
        run: docker-compose up -d --force-recreate

      - name: Remove dangling-images
        run: dng=$(docker images -f "dangling=true" -q | wc -l); if [[ $dng != 0 ]] ; then docker rmi -f $(docker images -f "dangling=true" -q); else echo "No danglings found"; fi
  


