name: Full remote 

on:
  workflow_dispatch:
      
jobs:
  stop_prev_cont:
    name: stop previous container
    runs-on: self-hosted
  
    steps:
      - name: sdf
        run: docker stop mspwebsite
    
  build:
    name: image build
    runs-on: self-hosted
    
    steps:
      - name: checking for actual
        uses: actions/checkout@v2.4.0
        with:
          path: .
        
      - name: building
        run: pwd
        
      - name: whoami
        run: echo $USER
        
      - name: helloworld
        run: docker run -rm hello-world
    
  


