name: Full remote 

on:
  workflow_dispatch:
  
jobs:
  stop_prev_cont:
    name: stop previous container
    runs-on: self-hosted
    steps:
      - name: container stop
        run: docker stop ${{env.IMAGE.NAME}}
        
      - name: image remove
        run: docker rmi ${{env.IMAGE.NAME}}
    
  build:
    if: ${{ always() }}
    needs: stop_prev_cont
    name: image build
    runs-on: self-hosted
    steps:
      - name: checking for actual
        uses: actions/checkout@v2.4.0
        with:
          path: .
        
      - name: building
        run: docker build -t ${{env.IMAGE.NAME}} .
        
      - name: running
        run: docker run --name ${{env.IMAGE.NAME}} --rm -d -p 4000:80 ${{env.IMAGE.NAME}}

    
  


