name: Github packages
 
on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_PATH: ${{ github.repository }}
  IMAGE_NAME: mspolyak-website

  
jobs:
  build-and-push:
    name: GitHub-runner
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        
      - name: login
        uses: docker/login-action@v1.13.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

#      - name: Extracting metadata
#        id: meta
#        uses: docker/metadata-action@v3.6.2
#        with:
#          images: ${{ env.Registry }}/${{ env.IMAGE_PATH }}

      - name: Build and Push to Packages
        uses: docker/build-push-action@v2.9.0
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

    
  remote_stop:
    needs: build-and-push
    name: remote-stopper
    runs-on: self-hosted
    
    steps:
      - name: container stop
        run: docker stop ${{env.IMAGE_NAME}}

      - name: rmi
        run: docker rmi ${{env.IMAGE_NAME}}


  remote_run:
    if: ${{ always() }}
    needs: remote_stop
    name: remote-runner
    runs-on: self-hosted
    
    steps:
      - name: docker pull
        run: docker pull ${{ env.Registry }}/${{ env.IMAGE_NAME }}

      - name: run
        run: docker run --name ${{env.IMAGE_NAME}} --rm -d -p 4000:80 ${{env.IMAGE_NAME}}
  


