name: Full remote 

on:
  workflow_dispatch:
      
jobs:
  container_rebuild:
    name: current cnt -> rebuilded cnt
    runs-on: self-hosted
    steps:
      - name: container stop
        run: docker stop mspwebsite
        
      - name: image remove
        run: docker rmi mspwebsite
    
      - name: checking for actual
        uses: actions/checkout@v2.4.0
        with:
          path: .
        
      - name: building new container
        run: docker build -t mspwebsite .
        
      - name: running new container
        run: docker run --name mspwebsite --rm -d -p 4000:80 mspwebsite

    
  


